version: "3.7"
services:
#  app:
#    build: .
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
#    links:
#      - db:rlvbvwgj
  db:
    image: "postgres:11.4"
    ports:
      - 5432:8080
    environment:
      PGHOST: localhost
      PGDATABASE: rlvbvwgj
      PGPASSWORD: 2fn_aiDT0BEDUwIigB2HUlxFGBOxf-ww
      PGUSER: rlvbvwgj

